version: '3'
services:
  elasticsearch:
    image: es-java-sample:latest
    container_name: es-java-sample
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: es-java-sample-kibana:latest
    container_name: es-java-sample-kibana
    ports:
      - 5601:5601

  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - 3307:3306
    volumes:
      - ./db/mysql_init:/docker-entrypoint-initdb.d
      - ./db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: qiita
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql

  app:
    image: es-java-sample-app:latest
    container_name: es-java-sample-app
    ports:
      - 8081:8080
    depends_on:
      - elasticsearch
volumes:
  esdata:
    driver: local